"""add the poster_path and backdrop_path attribute to the movide model

Revision ID: 066fbd842517
Revises: 8fcaf7a0d00c
Create Date: 2024-10-17 14:13:24.276281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066fbd842517'
down_revision: Union[str, None] = '8fcaf7a0d00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_path', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('backdrop_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'backdrop_path')
    op.drop_column('movies', 'poster_path')
    # ### end Alembic commands ###
