"""made genre name length increase

Revision ID: 0bf6bf0029aa
Revises: b7e7814b5945
Create Date: 2024-10-17 19:27:53.553509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bf6bf0029aa'
down_revision: Union[str, None] = 'b7e7814b5945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('movie_status')
    # op.drop_index('name', table_name='genres')
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'trailer_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('movies', 'duration_in_min',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # op.drop_index('u_id', table_name='movies')
    # op.create_index('ix_movies_summary', 'movies', ['summary'], unique=False, mysql_length=255)
    # op.create_index(op.f('ixmovies_release_date'), 'movies', ['release_date'], unique=False)
    # op.create_index(op.f('ixmovies_status'), 'movies', ['status'], unique=False)
    # op.create_index(op.f('ixmovies_summary'), 'movies', ['summary'], unique=False)
    # op.create_index(op.f('ixmovies_tagline'), 'movies', ['tagline'], unique=False)
    # op.create_index(op.f('ixmovies_title'), 'movies', ['title'], unique=False)
    op.create_unique_constraint(op.f('uq_movies_u_id'), 'movies', ['u_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_movies_u_id'), 'movies', type_='unique')
    op.drop_index(op.f('ixmovies_title'), table_name='movies')
    op.drop_index(op.f('ixmovies_tagline'), table_name='movies')
    op.drop_index(op.f('ixmovies_summary'), table_name='movies')
    op.drop_index(op.f('ixmovies_status'), table_name='movies')
    op.drop_index(op.f('ixmovies_release_date'), table_name='movies')
    op.drop_index('ix_movies_summary', table_name='movies', mysql_length=255)
    op.create_index('u_id', 'movies', ['u_id'], unique=True)
    op.alter_column('movies', 'duration_in_min',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('movies', 'trailer_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index('name', 'genres', ['name'], unique=True)
    op.create_table('movie_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.ENUM('released', 'upcoming'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
