"""create theatre model

Revision ID: 1ddcb4110d41
Revises: 448be3963c3d
Create Date: 2024-10-15 15:11:42.416942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddcb4110d41'
down_revision: Union[str, None] = '448be3963c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatres',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'INSTAGRAM', 'X', 'FACEBOOK', name='theatresigninenum'), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('u_id', sa.String(length=21), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theatres')),
    sa.UniqueConstraint('id', name=op.f('uq_theatres_id')),
    sa.UniqueConstraint('u_id', name=op.f('uq_theatres_u_id'))
    )
    op.create_index(op.f('ixtheatres_email'), 'theatres', ['email'], unique=True)
    op.create_index(op.f('ixtheatres_name'), 'theatres', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ixtheatres_name'), table_name='theatres')
    op.drop_index(op.f('ixtheatres_email'), table_name='theatres')
    op.drop_table('theatres')
    # ### end Alembic commands ###
