"""made seat and booking a many to many relationship

Revision ID: 1ff0fe3baf61
Revises: 1b3a93cfb5bc
Create Date: 2024-11-05 13:46:38.861405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ff0fe3baf61'
down_revision: Union[str, None] = '1b3a93cfb5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_seat',
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_booking_seat_booking_id_booking')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_booking_seat_seat_id_seats'))
    )
    op.drop_table('seat_booked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_booked',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('row_name', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('available_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('theatrehall_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['theatrehall_id'], ['theatre_halls.id'], name='fk_seat_booked_theatrehall_id_theatre_halls'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('booking_seat')
    # ### end Alembic commands ###
