"""change column rows to row_name

Revision ID: 246e3f3f22b1
Revises: a6f54ca97ea9
Create Date: 2024-10-28 12:55:43.488207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '246e3f3f22b1'
down_revision: Union[str, None] = 'a6f54ca97ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('seats', 'rows')
    # op.add_column('seats', sa.Column('row_name', sa.String(length=1), nullable=False))
    # op.drop_constraint('uq_theatre_hall_row', 'seats', type_='unique')
    # op.create_unique_constraint('uq_theatre_hall_row', 'seats', ['theatre_hall_id', 'row_name'])
    # ### end Alembic commands ###
    ...


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('rows', mysql.VARCHAR(length=1), nullable=False))
    op.drop_constraint('uq_theatre_hall_row', 'seats', type_='unique')
    # op.create_unique_constraint('uq_theatre_hall_row', 'seats', ['theatre_hall_id', 'rows'])
    op.drop_column('seats', 'row_name')
    # ### end Alembic commands ###
