"""set default value of total_rows and seats_per_row

Revision ID: 2b66b26f0e53
Revises: 2cf2a5743070
Create Date: 2024-10-28 11:24:52.202363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b66b26f0e53'
down_revision: Union[str, None] = '2cf2a5743070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatre_halls', 'total_rows')
    op.drop_column('theatre_halls', 'seats_per_row')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_halls', sa.Column('seats_per_row', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('theatre_halls', sa.Column('total_rows', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
