"""make id string length 100

Revision ID: 2cd4e966df24
Revises: 99df0debc177
Create Date: 2024-10-14 15:01:06.999986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cd4e966df24'
down_revision: Union[str, None] = '99df0debc177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=34),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=34),
               existing_nullable=False)
    # ### end Alembic commands ###
