"""create seats status column

Revision ID: 2cf2a5743070
Revises: 4e45047f9756
Create Date: 2024-10-28 11:22:54.699404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf2a5743070'
down_revision: Union[str, None] = '4e45047f9756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'BOOKED', name='seatstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'status')
    # ### end Alembic commands ###
