"""add price attribute to the showtime model

Revision ID: 33b5e1bd99a4
Revises: 3c9d1588ef46
Create Date: 2024-11-06 12:24:29.151272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b5e1bd99a4'
down_revision: Union[str, None] = '3c9d1588ef46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_time', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show_time', 'price')
    # ### end Alembic commands ###
