"""remove seat_id from booking table

Revision ID: 3c9d1588ef46
Revises: deb919a587c6
Create Date: 2024-11-05 20:44:12.068073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c9d1588ef46'
down_revision: Union[str, None] = 'deb919a587c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_booking_seat_id_seats', 'booking', type_='foreignkey')
    op.drop_column('booking', 'seat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('seat_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_booking_seat_id_seats', 'booking', 'seats', ['seat_id'], ['id'])
    # ### end Alembic commands ###
