"""added user signin provider

Revision ID: 448be3963c3d
Revises: 2cd4e966df24
Create Date: 2024-10-14 16:30:53.050866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448be3963c3d'
down_revision: Union[str, None] = '2cd4e966df24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.Enum('GOOGLE', 'PASSWORD', name='signinprovider'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
