"""trailer link nullable

Revision ID: 4b2e13d40e89
Revises: f3f3d77f3083
Create Date: 2024-10-17 19:41:19.770746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b2e13d40e89'
down_revision: Union[str, None] = 'f3f3d77f3083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'trailer_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'trailer_link',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
