"""theatre hall and seat created

Revision ID: 4e45047f9756
Revises: 859d1285be44
Create Date: 2024-10-28 11:08:54.207216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e45047f9756'
down_revision: Union[str, None] = '859d1285be44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre_halls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('seats_per_row', sa.Integer(), nullable=False),
    sa.Column('theatre_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name=op.f('fk_theatre_halls_theatre_id_theatres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theatre_halls')),
    sa.UniqueConstraint('name', name=op.f('uq_theatre_halls_name'))
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rows', sa.String(length=1), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('theatre_hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theatre_hall_id'], ['theatre_halls.id'], name=op.f('fk_seats_theatre_hall_id_theatre_halls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('theatre_halls')
    # ### end Alembic commands ###
