"""create user model

Revision ID: 544692028957
Revises: 
Create Date: 2024-10-08 18:42:58.151645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544692028957'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.String(length=21), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('u_id', name=op.f('uq_users_u_id'))
    )
    op.create_index(op.f('ixusers_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ixusers_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ixusers_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ixusers_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ixusers_last_name'), table_name='users')
    op.drop_index(op.f('ixusers_id'), table_name='users')
    op.drop_index(op.f('ixusers_first_name'), table_name='users')
    op.drop_index(op.f('ixusers_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
