"""create seats model

Revision ID: 54a479d18e3c
Revises: 5a2613df5f2a
Create Date: 2024-10-28 13:07:15.479639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a479d18e3c'
down_revision: Union[str, None] = '5a2613df5f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_name', sa.String(length=1), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'BOOKED', name='seatstatus'), nullable=False),
    sa.Column('theatre_hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theatre_hall_id'], ['theatre_halls.id'], name=op.f('fk_seats_theatre_hall_id_theatre_halls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('row_name', 'seat', name='uq_row_name_seat_row')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
