"""create unique constraint for seats and row name

Revision ID: 66c344ab5a0c
Revises: d13127ddffd3
Create Date: 2024-10-28 13:05:09.083275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c344ab5a0c'
down_revision: Union[str, None] = 'd13127ddffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uq_theatre_hall_row', table_name='seats')
    op.create_unique_constraint('uq_row_name_seat_row', 'seats', ['row_name', 'seat'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_row_name_seat_row', 'seats', type_='unique')
    op.create_index('uq_theatre_hall_row', 'seats', ['theatre_hall_id', 'row_name'], unique=True)
    # ### end Alembic commands ###
