"""relationship with theatre hall and booking

Revision ID: 6b28cc6d4aaf
Revises: 7fcd5e7d1cee
Create Date: 2024-10-29 21:28:20.748027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b28cc6d4aaf'
down_revision: Union[str, None] = '7fcd5e7d1cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
