"""relationship with theatre hall and booking

Revision ID: 7270527052f0
Revises: 6b28cc6d4aaf
Create Date: 2024-10-29 21:33:55.558298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7270527052f0'
down_revision: Union[str, None] = '6b28cc6d4aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
