"""create the showtime model

Revision ID: 74d793e17252
Revises: 17e19a3182cf
Create Date: 2024-10-28 18:28:59.572408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d793e17252'
down_revision: Union[str, None] = '17e19a3182cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('theatre_hall_id', sa.Integer(), nullable=False),
    sa.Column('stream_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_show_time_movie_id_movies')),
    sa.ForeignKeyConstraint(['theatre_hall_id'], ['theatre_halls.id'], name=op.f('fk_show_time_theatre_hall_id_theatre_halls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show_time')),
    sa.UniqueConstraint('u_id', name=op.f('uq_show_time_u_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_time')
    # ### end Alembic commands ###
