"""change tag to tagline

Revision ID: 7b9cd24c6e46
Revises: 200484942e89
Create Date: 2024-10-17 17:04:37.327224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b9cd24c6e46'
down_revision: Union[str, None] = '200484942e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tag_line', sa.String(length=50), nullable=True))
    op.drop_index('ixmovies_tags', table_name='movies')
    op.create_index(op.f('ixmovies_tag_line'), 'movies', ['tag_line'], unique=False)
    op.drop_column('movies', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tags', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ixmovies_tag_line'), table_name='movies')
    op.create_index('ixmovies_tags', 'movies', ['tags'], unique=False)
    op.drop_column('movies', 'tag_line')
    # ### end Alembic commands ###
