"""added id to movie_genre table

Revision ID: 845401e3aa6d
Revises: 4b2e13d40e89
Create Date: 2024-10-17 19:45:12.673581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '845401e3aa6d'
down_revision: Union[str, None] = '4b2e13d40e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_genres', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('movie_genres', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
