"""made theatre admin

Revision ID: 859d1285be44
Revises: 845401e3aa6d
Create Date: 2024-10-18 12:11:05.119464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '859d1285be44'
down_revision: Union[str, None] = '845401e3aa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatres', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('theatres', 'is_admin')
    # ### end Alembic commands ###
