"""change column name seats to seat

Revision ID: 88281101b849
Revises: 9e292c91be34
Create Date: 2024-10-28 12:21:59.175863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88281101b849'
down_revision: Union[str, None] = '9e292c91be34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('seat', sa.Integer(), nullable=False))
    op.drop_column('seats', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('seats', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('seats', 'seat')
    # ### end Alembic commands ###
