"""made available seat column nullable

Revision ID: 8fbd8e3dd51b
Revises: b23a6971aced
Create Date: 2024-11-05 16:29:45.693991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fbd8e3dd51b'
down_revision: Union[str, None] = 'b23a6971aced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seat_booked', 'available_seats',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seat_booked', 'available_seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
