"""change id from int to uuid

Revision ID: 913ed8e0cf70
Revises: 544692028957
Create Date: 2024-10-14 08:23:52.347736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '913ed8e0cf70'
down_revision: Union[str, None] = '544692028957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=34),
               existing_nullable=False)
    op.drop_index('ixusers_id', table_name='users')
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.create_index('ixusers_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=34),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
