"""remove status column

Revision ID: 9b1af2f12264
Revises: a3c38e6f7a9b
Create Date: 2024-10-29 15:31:09.018750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b1af2f12264'
down_revision: Union[str, None] = 'a3c38e6f7a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixmovies_status', table_name='movies')
    op.drop_column('movies', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('status', mysql.ENUM('released', 'upcoming'), nullable=False))
    op.create_index('ixmovies_status', 'movies', ['status'], unique=False)
    # ### end Alembic commands ###
