"""add column constraints to both total_rows and seats_per_row also add unique constraints to theatre_hall_id and rows

Revision ID: 9e292c91be34
Revises: b3b6845a9f94
Create Date: 2024-10-28 11:36:46.430415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e292c91be34'
down_revision: Union[str, None] = 'b3b6845a9f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_theatre_hall_row', 'seats', ['theatre_hall_id', 'rows'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_theatre_hall_row', 'seats', type_='unique')
    # ### end Alembic commands ###
