"""create movie, cast, genre, and director model

Revision ID: a106eb3f72f7
Revises: c369b9fe71b3
Create Date: 2024-10-17 11:41:26.615138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a106eb3f72f7'
down_revision: Union[str, None] = 'c369b9fe71b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('profile_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_casts'))
    )
    op.create_index(op.f('ixcasts_name'), 'casts', ['name'], unique=False)
    op.create_table('directors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('profile_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directors'))
    )
    op.create_index(op.f('ixdirectors_name'), 'directors', ['name'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('trailer_link', sa.String(length=100), nullable=False),
    sa.Column('duration_in_min', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('RELEASED', 'UPCOMING', name='moviestatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies')),
    sa.UniqueConstraint('u_id', name=op.f('uq_movies_u_id'))
    )
    op.create_index(op.f('ixmovies_release_date'), 'movies', ['release_date'], unique=False)
    op.create_index(op.f('ixmovies_status'), 'movies', ['status'], unique=False)
    op.create_index(op.f('ixmovies_summary'), 'movies', ['summary'], unique=False, mysql_length=255)
    op.create_index(op.f('ixmovies_tags'), 'movies', ['tags'], unique=False)
    op.create_index(op.f('ixmovies_title'), 'movies', ['title'], unique=False)
    op.create_table('movie_casts',
    sa.Column('cast_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cast_id'], ['casts.id'], name=op.f('fk_movie_casts_cast_id_casts')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_casts_movie_id_movies'))
    )
    op.create_table('movie_directors',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], name=op.f('fk_movie_directors_director_id_directors')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_directors_movie_id_movies'))
    )
    op.create_table('movie_genres',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genres_movie_id_movies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genres')
    op.drop_table('movie_directors')
    op.drop_table('movie_casts')
    op.drop_index(op.f('ixmovies_title'), table_name='movies')
    op.drop_index(op.f('ixmovies_tags'), table_name='movies')
    op.drop_index(op.f('ixmovies_summary'), table_name='movies')
    op.drop_index(op.f('ixmovies_status'), table_name='movies')
    op.drop_index(op.f('ixmovies_release_date'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_index(op.f('ixdirectors_name'), table_name='directors')
    op.drop_table('directors')
    op.drop_index(op.f('ixcasts_name'), table_name='casts')
    op.drop_table('casts')
    # ### end Alembic commands ###
