"""change column total_rows to total_row

Revision ID: a6f54ca97ea9
Revises: 2e2621fb6233
Create Date: 2024-10-28 12:54:29.235968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6f54ca97ea9'
down_revision: Union[str, None] = '2e2621fb6233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_halls', sa.Column('total_row', sa.Integer(), nullable=False))
    op.drop_column('theatre_halls', 'total_rows')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_halls', sa.Column('total_rows', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('theatre_halls', 'total_row')
    # ### end Alembic commands ###
