"""create seat booking model

Revision ID: b23a6971aced
Revises: 1ff0fe3baf61
Create Date: 2024-11-05 16:28:33.136130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23a6971aced'
down_revision: Union[str, None] = '1ff0fe3baf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_booked',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_name', sa.String(length=1), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('theatrehall_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['theatrehall_id'], ['theatre_halls.id'], name=op.f('fk_seat_booked_theatrehall_id_theatre_halls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seat_booked'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_booked')
    # ### end Alembic commands ###
