"""set default value of total_rows and seats_per_row

Revision ID: b3b6845a9f94
Revises: 2b66b26f0e53
Create Date: 2024-10-28 11:26:07.350673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b6845a9f94'
down_revision: Union[str, None] = '2b66b26f0e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatre_halls', sa.Column('total_rows', sa.Integer(), nullable=False))
    op.add_column('theatre_halls', sa.Column('seats_per_row', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatre_halls', 'seats_per_row')
    op.drop_column('theatre_halls', 'total_rows')
    # ### end Alembic commands ###
