"""create the address model and relationships

Revision ID: b94de0388fa2
Revises: 1859264d9877
Create Date: 2024-10-16 16:32:25.584541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94de0388fa2'
down_revision: Union[str, None] = '1859264d9877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ixaddress_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ixaddress_state'), 'address', ['state'], unique=False)
    op.create_index(op.f('ixaddress_street_address'), 'address', ['street_address'], unique=False)
    op.create_table('theatre_address',
    sa.Column('theatre_id', sa.String(length=100), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_theatre_address_address_id_address')),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name=op.f('fk_theatre_address_theatre_id_theatres'), ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theatre_address')
    op.drop_index(op.f('ixaddress_street_address'), table_name='address')
    op.drop_index(op.f('ixaddress_state'), table_name='address')
    op.drop_index(op.f('ixaddress_city'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
