"""create unique ness for every row

Revision ID: be0c47d49cd1
Revises: 54a479d18e3c
Create Date: 2024-10-28 13:16:53.575240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0c47d49cd1'
down_revision: Union[str, None] = '54a479d18e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_row_name_seat_row', table_name='seats')
    op.create_unique_constraint('uq_theatre_hall_id_row_name_seat_row', 'seats', ['row_name', 'seat', 'theatre_hall_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_theatre_hall_id_row_name_seat_row', 'seats', type_='unique')
    op.create_index('uq_row_name_seat_row', 'seats', ['row_name', 'seat'], unique=True)
    # ### end Alembic commands ###
