"""create movie, cast, genre, and director model

Revision ID: c369b9fe71b3
Revises: b94de0388fa2
Create Date: 2024-10-17 11:40:39.636615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c369b9fe71b3'
down_revision: Union[str, None] = 'b94de0388fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
