"""made genre name unique

Revision ID: cb42fa5575da
Revises: 308f4de18a0f
Create Date: 2024-10-17 18:29:18.876456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb42fa5575da'
down_revision: Union[str, None] = '308f4de18a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_genres_name'), 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_genres_name'), 'genres', type_='unique')
    # ### end Alembic commands ###
