"""add movie status column

Revision ID: d90379dbdf54
Revises: 9b1af2f12264
Create Date: 2024-10-29 15:32:08.243633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90379dbdf54'
down_revision: Union[str, None] = '9b1af2f12264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('status', sa.Enum('RELEASED', 'UPCOMING', name='moviestatus'), nullable=False))
    op.create_index(op.f('ixmovies_status'), 'movies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ixmovies_status'), table_name='movies')
    op.drop_column('movies', 'status')
    # ### end Alembic commands ###
